version : '3.8'

services:
        website:
                image: php:7.2-apache
                container_name: website
                hostname: test.website
                ports:
                        - 8081:80
                networks:
                        robot :
                          ipv4_address: 172.28.1.3
                volumes:
                        - ./website/:/var/www/html/
                links:
                        - mysql_db
                
                restart: always
        mysql_db:
                image: mysql:5.7
                container_name: mysql_db
                ports:
                        - 6603:3306
                environment: 
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_USER=brijesh
                        - MYSQL_PASSWORD=brijesh
                        - MYSQL_DATABASE=registration
                volumes:
                        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
                networks:
                        robot :
                          ipv4_address: 172.28.1.4
                restart: always

        phpmyadmin:
                image: phpmyadmin/phpmyadmin:latest
                container_name: phpmyadmin
                ports:
                        - 8083:80
                depends_on:
                        - mysql_db
                environment:
                        PMA_HOST: mysql_db
                networks:
                        robot :
                          ipv4_address: 172.28.1.5
                restart: always

volumes: 
        website:
        robotframework:

networks:
        robot:
                ipam: 
                        driver: default
                        config:
                                - subnet: 172.28.0.0/16
                    
